
services:
  my_sql:
    image: mysql:8.0
    container_name: phishing-scan-platform-db
    env_file:
      - app_data/.env_user_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s

  web:
    container_name: python_web_service_app
    build: .
    depends_on:
      my_sql:
        condition: service_healthy
    environment:
      MYSQL_HOST: phishing-scan-platform-db
      PYTHONPATH: /app
      
    ports:
      - "1234:1234"
    networks:
      - my_network
    command: ["sh", "-c", "/app/wait-for-it.sh phishing-scan-platform-db 3306 python app.py"]



    
networks:
  my_network: {}  # ✅ Corrected to a valid mapping

volumes:
  mysql_data:  # ✅ Named volume for persistence
